import {useState} from 'react';
import {useParams} from 'react-router-dom';
import {Bell,CalendarCheck,Check,ClipboardCheck,Save,Send,Users} from 'lucide-react';
import {api} from '../../api';
import {useAuth} from '../../auth';
import {Badge,Button,Card,Empty,ErrorBox,Field,Loading,Page,Table,useLoad} from '../../components';

export default function TeacherWorkspace(){const {section}=useParams();const {user}=useAuth();const common=useLoad(async()=>{const [assignments,schedule,classes,subjects,semesters,allAssignments,allStudents]=await Promise.all([api.get(`/api/teacher/assignments?teacherId=${user.id}`),api.get(`/api/teacher/schedule?teacherId=${user.id}`),api.get('/api/admin/classes'),api.get('/api/admin/subjects'),api.get('/api/admin/semesters'),api.get('/api/admin/assignments'),api.get('/api/admin/students')]);return {assignments,schedule,classes,subjects,semesters,allAssignments,allStudents,homeroom:classes.filter(c=>c.homeroomTeacherId===user.id)}},[user.id]);if(common.loading)return <Loading/>;if(common.error)return <ErrorBox error={common.error} onRetry={common.reload}/>;const props={user,data:common.data};if(section==='schedule')return <Schedule {...props}/>;if(section==='classes')return <Classes {...props}/>;if(section==='grades')return <Grades {...props}/>;if(section==='attendance')return <Attendance {...props}/>;if(section==='notifications')return <Notifications {...props}/>;return <Homeroom {...props}/>}

const label=(a,d)=>`${d.classes.find(c=>c.id===a.classId)?.name} · ${d.subjects.find(s=>s.id===a.subjectId)?.name}`;
function Picker({assignments,data,value,onChange,labelText='Phân công'}){return <Field label={labelText}><select value={value} onChange={e=>onChange(Number(e.target.value))}><option value="">Chọn lớp và môn...</option>{assignments.map(a=><option key={a.id} value={a.id}>{label(a,data)}</option>)}</select></Field>}
function Schedule({data}){const rows=data.schedule.map(s=>{const a=data.assignments.find(a=>a.id===s.teacherAssignmentId);return {...s,className:data.classes.find(c=>c.id===a?.classId)?.name,subject:data.subjects.find(x=>x.id===a?.subjectId)?.name}});return <Page title="Lịch dạy" subtitle="Thời khóa biểu cá nhân theo tuần"><Card><Table rows={rows} columns={[{key:'dayOrder',label:'Ngày',render:x=>x.dayOrder===8?'Chủ nhật':`Thứ ${x.dayOrder}`},{key:'period',label:'Tiết'},{key:'subject',label:'Môn học'},{key:'className',label:'Lớp'},{key:'room',label:'Phòng'},{key:'time',label:'Thời gian',render:x=>`${x.startTime} – ${x.endTime}`}]}/></Card></Page>}
function Classes({user,data}){const [selected,setSelected]=useState(data.assignments[0]?.id||'');const current=data.assignments.find(a=>a.id===selected);const state=useLoad(()=>selected?api.get(`/api/teacher/assignments/${selected}/students?teacherId=${user.id}`):Promise.resolve([]),[selected]);return <Page title="Lớp giảng dạy" subtitle="Danh sách học sinh theo phân công"><Card className="toolbar-card"><Picker assignments={data.assignments} data={data} value={selected} onChange={setSelected}/>{current&&<Badge tone="blue">{state.data?.length||0} học sinh</Badge>}</Card><Card>{state.loading?<Loading/>:<Table rows={state.data||[]} columns={[{key:'studentCode',label:'Mã HS'},{key:'fullName',label:'Họ và tên'},{key:'dateOfBirth',label:'Ngày sinh'},{key:'gender',label:'Giới tính',render:x=>x.gender==='MALE'?'Nam':'Nữ'}]}/>}</Card></Page>}

function Grades({user,data}){const [selected,setSelected]=useState(data.assignments[0]?.id||'');const state=useLoad(async()=>{if(!selected)return [];const [students,grades]=await Promise.all([api.get(`/api/teacher/assignments/${selected}/students?teacherId=${user.id}`),api.get(`/api/teacher/assignments/${selected}/grades?teacherId=${user.id}`)]);return students.map(s=>({...s,grade:grades.find(g=>g.studentId===s.id)}))},[selected]);const save=async(row,field,value)=>{const g={...(row.grade||{}),[field]:value===''?null:(field==='regularScores'?value:Number(value))};await api.put(`/api/teacher/assignments/${selected}/students/${row.id}/grade?teacherId=${user.id}`,g);state.reload()};return <Page title="Quản lý điểm" subtitle="Nhập điểm cho đúng lớp và môn được phân công"><Card className="toolbar-card"><Picker assignments={data.assignments} data={data} value={selected} onChange={setSelected}/></Card><Card>{state.loading?<Loading/>:<div className="table-wrap"><table><thead><tr><th>Học sinh</th><th>Thường xuyên</th><th>Giữa kỳ</th><th>Cuối kỳ</th><th>Trung bình</th></tr></thead><tbody>{(state.data||[]).map(row=><tr key={row.id}><td><strong>{row.fullName}</strong><small className="block">{row.studentCode}</small></td>{['regularScores','midtermScore','finalScore'].map(f=><td key={f}><input className="score-input" defaultValue={row.grade?.[f]??''} onBlur={e=>save(row,f,e.target.value)} placeholder="—"/></td>)}<td><Badge tone="blue">{row.grade?.averageScore??'Chưa có'}</Badge></td></tr>)}</tbody></table></div>}</Card></Page>}

function Attendance({user,data}){const [scheduleId,setScheduleId]=useState(data.schedule[0]?.id||'');const [date,setDate]=useState(new Date().toISOString().slice(0,10));const schedule=data.schedule.find(s=>s.id===scheduleId);const assignment=data.assignments.find(a=>a.id===schedule?.teacherAssignmentId);const state=useLoad(async()=>{if(!scheduleId||!assignment)return [];const [students,marked]=await Promise.all([api.get(`/api/teacher/assignments/${assignment.id}/students?teacherId=${user.id}`),api.get(`/api/teacher/schedules/${scheduleId}/attendance?teacherId=${user.id}&date=${date}`)]);return students.map(s=>({...s,status:marked.find(x=>x.studentId===s.id)?.status||'PRESENT'}))},[scheduleId,date]);const [rows,setRows]=useState(null);const current=rows||state.data||[];const save=async()=>{await api.put(`/api/teacher/schedules/${scheduleId}/attendance?teacherId=${user.id}&date=${date}`,current.map(x=>({studentId:x.id,status:x.status})));alert('Đã lưu điểm danh');state.reload();setRows(null)};return <Page title="Điểm danh" subtitle="Ghi nhận tình trạng học sinh theo tiết học" action={<Button onClick={save} disabled={!current.length}><Save size={17}/> Lưu điểm danh</Button>}><Card className="toolbar-card"><Field label="Tiết học"><select value={scheduleId} onChange={e=>{setScheduleId(Number(e.target.value));setRows(null)}}>{data.schedule.map(s=>{const a=data.assignments.find(a=>a.id===s.teacherAssignmentId);return <option key={s.id} value={s.id}>Thứ {s.dayOrder} · Tiết {s.period} · {label(a,data)}</option>})}</select></Field><Field label="Ngày điểm danh"><input type="date" value={date} onChange={e=>{setDate(e.target.value);setRows(null)}}/></Field></Card><Card>{state.loading?<Loading/>:<Table rows={current} columns={[{key:'studentCode',label:'Mã HS'},{key:'fullName',label:'Họ và tên'},{key:'status',label:'Trạng thái',render:r=><select className="status-select" value={r.status} onChange={e=>setRows(current.map(x=>x.id===r.id?{...x,status:e.target.value}:x))}><option value="PRESENT">Có mặt</option><option value="ABSENT">Vắng</option><option value="LATE">Đi muộn</option><option value="EXCUSED">Có phép</option></select>} ]}/>}</Card></Page>}

function Notifications({user,data}){const classIds=[...new Set(data.assignments.map(a=>a.classId).concat(data.homeroom.map(c=>c.id)))];const [form,setForm]=useState({classId:classIds[0]||'',title:'',content:''});const send=async e=>{e.preventDefault();await api.post(`/api/teacher/classes/${form.classId}/notifications?teacherId=${user.id}`,form);setForm({...form,title:'',content:''});alert('Đã gửi thông báo')};return <Page title="Gửi thông báo" subtitle="Thông báo tới các lớp thầy/cô đang phụ trách"><div className="narrow"><Card><form className="stack-form" onSubmit={send}><Field label="Lớp nhận"><select value={form.classId} onChange={e=>setForm({...form,classId:Number(e.target.value)})}>{classIds.map(id=><option key={id} value={id}>{data.classes.find(c=>c.id===id)?.name}</option>)}</select></Field><Field label="Tiêu đề"><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></Field><Field label="Nội dung"><textarea rows="7" value={form.content} onChange={e=>setForm({...form,content:e.target.value})} required/></Field><Button><Send size={17}/> Gửi thông báo</Button></form></Card></div></Page>}

function Homeroom({user,data}){const [classId,setClassId]=useState(data.homeroom[0]?.id||'');const [tab,setTab]=useState('leaves');if(!data.homeroom.length)return <Page title="Công tác chủ nhiệm"><Card><Empty text="Thầy/cô hiện không được phân công chủ nhiệm lớp nào"/></Card></Page>;return <Page title="Công tác chủ nhiệm" subtitle="Duyệt đơn, xem điểm tổng hợp và đánh giá học sinh"><Card className="toolbar-card"><Field label="Lớp chủ nhiệm"><select value={classId} onChange={e=>setClassId(Number(e.target.value))}>{data.homeroom.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><div className="tabs"><button className={tab==='leaves'?'active':''} onClick={()=>setTab('leaves')}>Đơn xin nghỉ</button><button className={tab==='grades'?'active':''} onClick={()=>setTab('grades')}>Bảng điểm lớp</button><button className={tab==='evaluation'?'active':''} onClick={()=>setTab('evaluation')}>Đánh giá cuối kỳ</button></div></Card>{tab==='leaves'?<Leaves user={user} classId={classId} data={data}/>:tab==='grades'?<ClassGrades user={user} classId={classId} data={data}/>:<Evaluations user={user} classId={classId} data={data}/>}</Page>}
function Leaves({user,classId,data}){const state=useLoad(()=>api.get(`/api/teacher/homeroom/${classId}/leaves?teacherId=${user.id}`),[classId]);const review=async(id,status)=>{await api.put(`/api/teacher/homeroom/${classId}/leaves/${id}?teacherId=${user.id}`,{status,rejectionReason:status==='REJECTED'?'GVCN từ chối đơn':null});state.reload()};return <Card>{state.loading?<Loading/>:<Table rows={state.data||[]} columns={[{key:'studentId',label:'Học sinh',render:x=>data.allStudents.find(s=>s.id===x.studentId)?.fullName||`HS #${x.studentId}`},{key:'date',label:'Thời gian',render:x=>`${x.fromDate} → ${x.toDate}`},{key:'reason',label:'Lý do'},{key:'status',label:'Trạng thái',render:x=><Badge tone={x.status==='APPROVED'?'green':x.status==='REJECTED'?'red':'orange'}>{x.status}</Badge>},{key:'actions',label:'',render:x=>x.status==='PENDING'?<div className="row-actions"><button onClick={()=>review(x.id,'APPROVED')}><Check size={15}/> Duyệt</button><button className="danger" onClick={()=>review(x.id,'REJECTED')}>Từ chối</button></div>:null}]}/>}</Card>}
function ClassGrades({user,classId,data}){const state=useLoad(()=>api.get(`/api/teacher/homeroom/${classId}/grades?teacherId=${user.id}`),[classId]);return <Card>{state.loading?<Loading/>:<Table rows={state.data||[]} columns={[{key:'studentId',label:'Học sinh',render:x=>data.allStudents.find(s=>s.id===x.studentId)?.fullName||`HS #${x.studentId}`},{key:'subject',label:'Môn học',render:x=>{const a=data.allAssignments.find(a=>a.id===x.teacherAssignmentId);return data.subjects.find(s=>s.id===a?.subjectId)?.name||`#${x.teacherAssignmentId}`}},{key:'regularScores',label:'Thường xuyên'},{key:'midtermScore',label:'Giữa kỳ'},{key:'finalScore',label:'Cuối kỳ'},{key:'averageScore',label:'Trung bình'}]}/>}</Card>}
function Evaluations({user,classId,data}){const semester=data.semesters.find(s=>s.active)||data.semesters[0];const roster=useLoad(async()=>{if(!semester)return [];const evaluations=await api.get(`/api/teacher/homeroom/${classId}/evaluations?teacherId=${user.id}&semesterId=${semester.id}`);return data.allStudents.filter(s=>s.classId===classId).map(s=>({...s,evaluation:evaluations.find(e=>e.studentId===s.id)}))},[classId,semester?.id]);const save=async(row,rating)=>{await api.put(`/api/teacher/homeroom/${classId}/students/${row.id}/evaluation?teacherId=${user.id}&semesterId=${semester.id}`,{conductRating:rating,academicRating:row.evaluation?.academicRating||null,comment:row.evaluation?.comment||''});roster.reload()};return <Card>{roster.loading?<Loading/>:<Table rows={roster.data||[]} columns={[{key:'studentCode',label:'Mã HS'},{key:'fullName',label:'Họ và tên'},{key:'conduct',label:'Hạnh kiểm',render:r=><select className="status-select" value={r.evaluation?.conductRating||''} onChange={e=>save(r,e.target.value)}><option value="">Chọn...</option><option value="EXCELLENT">Tốt</option><option value="GOOD">Khá</option><option value="AVERAGE">Trung bình</option><option value="WEAK">Yếu</option></select>} ]}/>}</Card>}
